# タスク1: Thing・X.509証明書・IoTポリシー (Phase 1)
#
# トピック設計: vf/<equipment_id>/<sensor_id>
#   データモデルのタグ2つ (equipment_id / sensor_id) をそのままトピック階層に写す。
#   ポリシーは「証明書に紐づく Thing 名の場所」にしか publish できないよう縛る。
#
# 機密の注意: aws_iot_certificate の秘密鍵は tfstate に平文で入る。
#   本リポジトリは tfstate をローカル保持+gitignore で扱う (個人検証の割り切り)。
#   本番なら state は S3+暗号化、そもそも鍵はデバイス内生成 (CSR 方式) が筋。
#   → docs/ 非機能設計文書に記載予定

data "aws_caller_identity" "current" {}

data "aws_iot_endpoint" "data" {
  endpoint_type = "iot:Data-ATS"
}

# TLS 用 Amazon ルート CA。手動ダウンロードを再現手順から排除するため Terraform が取得する
data "http" "amazon_root_ca" {
  url = "https://www.amazontrust.com/repository/AmazonRootCA1.pem"
}

resource "aws_iot_thing" "sensor" {
  for_each = var.sensor_thing_names
  name     = each.key
}

resource "aws_iot_certificate" "sensor" {
  for_each = var.sensor_thing_names
  active   = true
}

# 「デバイスは自分としてしか喋れない」縛り:
#  - Connect: クライアントID = 証明書に紐づく Thing 名のみ。未紐付け証明書は接続自体を拒否 (IsAttached)
#  - Publish: vf/<任意のequipment>/<自分のThing名> のトピックのみ
#  - Subscribe/Receive は与えない (センサーは送るだけ。購読はブリッジ側の別ポリシー)
resource "aws_iot_policy" "sensor" {
  name = "${var.project}-sensor-policy"
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["iot:Connect"]
        Resource = ["arn:aws:iot:${var.region}:${data.aws_caller_identity.current.account_id}:client/$${iot:Connection.Thing.ThingName}"]
        Condition = {
          Bool = { "iot:Connection.Thing.IsAttached" = "true" }
        }
      },
      {
        Effect   = "Allow"
        Action   = ["iot:Publish"]
        Resource = ["arn:aws:iot:${var.region}:${data.aws_caller_identity.current.account_id}:topic/${var.project}/*/$${iot:Connection.Thing.ThingName}"]
      }
    ]
  })
}

resource "aws_iot_policy_attachment" "sensor" {
  for_each = var.sensor_thing_names
  policy   = aws_iot_policy.sensor.name
  target   = aws_iot_certificate.sensor[each.key].arn
}

resource "aws_iot_thing_principal_attachment" "sensor" {
  for_each  = var.sensor_thing_names
  thing     = aws_iot_thing.sensor[each.key].name
  principal = aws_iot_certificate.sensor[each.key].arn
}

# 証明書一式を ../certs/<thing名>/ に配置 (gitignore 済みディレクトリ)。
# compose が ./certs/<thing名>:/certs:ro でマウントする前提の配置
resource "local_file" "cert_pem" {
  for_each        = var.sensor_thing_names
  content         = aws_iot_certificate.sensor[each.key].certificate_pem
  filename        = "${path.module}/../certs/${each.key}/certificate.pem"
  file_permission = "0644"
}

resource "local_sensitive_file" "private_key" {
  for_each        = var.sensor_thing_names
  content         = aws_iot_certificate.sensor[each.key].private_key
  filename        = "${path.module}/../certs/${each.key}/private.key"
  file_permission = "0600"
}

resource "local_file" "root_ca" {
  for_each        = var.sensor_thing_names
  content         = data.http.amazon_root_ca.response_body
  filename        = "${path.module}/../certs/${each.key}/AmazonRootCA1.pem"
  file_permission = "0644"
}

# IoT エンドポイントはアカウント固有 URL のため、コードにベタ書きせず .env 経由で compose へ渡す
resource "local_file" "dotenv" {
  content         = <<-ENV
    # generated by terraform - do not commit (.gitignore 済み)
    IOT_ENDPOINT=${data.aws_iot_endpoint.data.endpoint_address}
  ENV
  filename        = "${path.module}/../.env"
  file_permission = "0644"
}
